name: Publish 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore
      run: dotnet restore ./CiCdDemo.sln
    - name: Build
      run: dotnet build ./CiCdDemo.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ./CiCdDemo.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH}}'
  Dev:
    runs-on: ubuntu-latest
    environment: DEV
    needs: publish
    steps:
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}
  Qa:
    runs-on: ubuntu-latest
    environment: QA
    needs: Dev
    steps:
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}
        
      
    
    
      
      
    
    
    
    
